// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProviderNotCleaned;

namespace ProviderNotCleaned.Migrations._3._0._0preview7
{
    [DbContext(typeof(ProviderNotCleanedContext))]
    [Migration("20190804143516_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview7.19362.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DummyModels.DummyModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("DummyModel");
                });

            modelBuilder.Entity("DummyModels.UniqueIdModel", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasMaxLength(36);

                    b.HasKey("UniqueId");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("UniqueIdModel");

                    b.HasData(
                        new
                        {
                            UniqueId = "8ac4b5f4-eac9-4fc7-b7a4-6a3ba0ae3556"
                        },
                        new
                        {
                            UniqueId = "509f3452-649f-4255-abb4-3608f3aa25db"
                        });
                });

            modelBuilder.Entity("DummyModels.DummyModel", b =>
                {
                    b.OwnsOne("DummyModels.OwnedModel", "OwnedModel", b1 =>
                        {
                            b1.Property<long>("DummyModelId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("RequiredField")
                                .IsRequired()
                                .HasColumnName("RequiredField");

                            b1.HasKey("DummyModelId");

                            b1.ToTable("DummyModel");

                            b1.WithOwner()
                                .HasForeignKey("DummyModelId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
