// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProviderNotCleaned;

namespace ProviderNotCleaned.Migrations._2._2._6
{
    [DbContext(typeof(ProviderNotCleanedContext))]
    partial class ProviderNotCleanedContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DummyModels.DummyModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("DummyModel");
                });

            modelBuilder.Entity("DummyModels.UniqueIdModel", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasMaxLength(36);

                    b.HasKey("UniqueId");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("UniqueIdModel");

                    b.HasData(
                        new
                        {
                            UniqueId = "8ac4b5f4-eac9-4fc7-b7a4-6a3ba0ae3556"
                        },
                        new
                        {
                            UniqueId = "509f3452-649f-4255-abb4-3608f3aa25db"
                        });
                });

            modelBuilder.Entity("DummyModels.DummyModel", b =>
                {
                    b.OwnsOne("DummyModels.OwnedModel", "OwnedModel", b1 =>
                        {
                            b1.Property<long>("DummyModelId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("RequiredField")
                                .IsRequired()
                                .HasColumnName("RequiredField");

                            b1.HasKey("DummyModelId");

                            b1.ToTable("DummyModel");

                            b1.HasOne("DummyModels.DummyModel")
                                .WithOne("OwnedModel")
                                .HasForeignKey("DummyModels.OwnedModel", "DummyModelId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
